spring.datasource.url=jdbc:postgresql://localhost:5432/accounting?user=liushukov.kirill
spring.datasource.username=liushukov.kirill
spring.datasource.driver-class-name=org.postgresql.Driver
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialization-mode=always
#spring.datasource.schema=classpath:/db/schema.sql
#spring.datasource.data=classpath:/db/data.sql
spring.jpa.hibernate.package-to-scan=com.petProject.Accounting.entities
spring.datasource.hikari.auto-commit=false
jwt.header=Authorization
jwt.secret=kirinho
jwt.expiration=1800







