spring.datasource.url=jdbc:postgresql://localhost:5432/accounting
spring.datasource.username=liushukov.kirill
spring.datasource.driver-class-name=org.postgresql.Driver
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialization-mode=always
spring.datasource.schema=classpath:/db/schema.sql
spring.datasource.data=classpath:/db/data.sql


